application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='articles')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ArticleList.as_view(), name='articles'),
    url(r'^category/$', views.CategoryList.as_view(), name='categories'),
    url(r'^category/(?P<slug>[\w-]+)/$', views.ArticleCategoryListView.as_view(), name='category_detail'),
    url(r'^post/(?P<slug>[\w-]+)/$', views.ArticleView.as_view(), name='article_detail'),

]

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=255, unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=255, db_index=True, unique=True, verbose_name='url')
    parent = TreeForeignKey('self', null=True, blank=True, verbose_name='подкатегория', db_index=True)

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255, db_index=True, verbose_name='Название статьи')
    slug = models.SlugField(max_length=255, db_index=True, unique=True, verbose_name='url')
    category = models.ForeignKey(Category, verbose_name='Категория')
    preview = RichTextUploadingField('Анонс статьи')
    text = RichTextUploadingField('Полная статья')
    pub_date = models.DateTimeField(verbose_name='Создан')

    class Meta:
        verbose_name = 'Статью'
        verbose_name_plural = 'Статьи'
        ordering = ("-pub_date", )

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from .models import Article, Category


class ArticleList(generic.ListView):
    model = Article
    template_name = 'blog/articles.html'


class ArticleView(generic.DetailView):
    model = Article
    context_object_name = 'article'
    template_name = 'blog/article.html'


class CategoryList(generic.ListView):
    model = Category
    template_name = 'blog/category.html'


class ArticleCategoryListView(generic.ListView):
    model = Article
    context_object_name = 'articles_category'
    template_name = 'blog/category_view.html'

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Article.objects.filter(category=self.category)

blog/templates/blog/article.html
{% extends 'blog/base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}
    <article class="article_block">
        <div class="article__pub_date">{{ article.pub_date }}</div>
        <h1 class="article__title">
             {{ article.title }}
        </h1>
        <div class="article__text">
            {{ article.text|safe }}
        </div>
    </article>
{% endblock %}

blog/templates/blog/articles.html
{% extends 'blog/base.html' %}
{% block title %} Блог {% endblock %}
{% block content %}
    {% for article in object_list %}
        <article class="article_item">
            <div class="article__title">
                <a href="{% url 'articles:category_detail' slug=article.category.slug %}" class="article_tag">{{ article.category.name }}</a><a href="{% url 'articles:article_detail' slug=article.slug %}">{{ article.title }}</a>
            </div>
            <div class="article__date">Добавлена: {{ article.pub_date }}</div>
        <div class="article__anonce">
            {{ article.preview|safe }}
        </div>
        </article>
    {% endfor %}

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Styles -->
      <link rel="stylesheet" href="{% static "blog/css/styles.css" %}">
</head>
<body>
    <header class="header">
        <a href="{% url 'articles:articles' %}" class="site_name">Блог</a>
        <nav class="top_navigation">
            <ul>
                <li>
                    <a href="#">Статьи</a>
                </li>
                 <li>
                    <a href="#">Портфолио</a>
                </li>
                 <li>
                    <a href="#">Обо мне</a>
                </li>
            </ul>
        </nav>

    </header>
    <main class="main">
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="copyright">
            copyright 2016
        </div>
    </footer>
</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block cat %}
{% for object in object_list %}
    <a href="{{ object.slug }}">{{ object.name }}</a>
{% endfor %}
{% endblock %}

blog/templates/blog/category_view.html
{% extends 'blog/base.html' %}
{% block title %} {{ category.name }} {% endblock %}
{% block content %}
{% for item in articles_category %}
    <article class="article_item">
            <div class="article__title">
                <a href="{% url 'articles:article_detail' slug=item.slug %}">{{ item.title }}</a>
            </div>
            <div class="article__date">Добавлена: {{ item.pub_date }}</div>
        <div class="article__anonce">
            {{ item.preview|safe }}
        </div>
        </article>
{% endfor %}



{% endblock %}